version: v0.1

listeners:
  ingress_traffic:
    address: 0.0.0.0
    port: 10000
    message_format: openai
    timeout: 30s

llm_providers:
  - name: gpt-4o
    access_key: $OPENAI_API_KEY
    provider_interface: openai
    model: gpt-4o

endpoints:
  frankfurther_api:
    endpoint: api.frankfurter.dev
    protocol: https

system_prompt: |
  You are a helpful assistant. Only respond to queries related to currency exchange. If there are any other questions, I can't help you.

prompt_guards:
  input_guards:
    jailbreak:
      on_exception:
        message: Looks like you're curious about my abilities, but I can only provide assistance for currency exchange.

prompt_targets:
  - name: currency_exchange
    description: Get currency exchange rate from USD to other currencies
    parameters:
      - name: currency_symbol
        description: currency symbol to convert from USD
        required: true
        type: str
        in_path: true
    endpoint:
      name: frankfurther_api
      path: /v1/latest?base=USD&symbols={currency_symbol}
    system_prompt: |
      You are a helpful assistant. Show me the currency symbol you want to convert from USD.

  - name: get_supported_currencies
    description: Get list of supported currencies for conversion
    endpoint:
      name: frankfurther_api
      path: /v1/currencies

tracing:
  random_sampling: 100
  trace_arch_internal: true
