$schema: "http://json-schema.org/draft-07/schema#"
type: object
properties:
  version:
    type: string
  listeners:
    type: object
    additionalProperties: false
    properties:
      ingress_traffic:
        type: object
        properties:
          address:
            type: string
          port:
            type: integer
          message_format:
            type: string
            enum:
              - openai
          timeout:
            type: string
        additionalProperties: false
      egress_traffic:
        type: object
        properties:
          address:
            type: string
          port:
            type: integer
          message_format:
            type: string
            enum:
              - openai
          timeout:
            type: string
        additionalProperties: false
  endpoints:
    type: object
    patternProperties:
      "^.*$":
        type: object
        properties:
          endpoint:
            type: string
          connect_timeout:
            type: string
          protocol:
            type: string
            enum:
              - http
              - https
          http_host:
            type: string
        additionalProperties: false
        required:
          - endpoint
  llm_providers:
    type: array
    items:
      type: object
      properties:
        name:
          type: string
        # provider field is deprecated, use provider_interface instead
        provider:
          type: string
          enum:
            - openai
        provider_interface:
          type: string
          enum:
            - openai
            - mistral
        access_key:
          type: string
        model:
          type: string
        default:
          type: boolean
        # endpoint field is deprecated, use base_url instead
        endpoint:
          type: string
        base_url:
          type: string
        protocol:
          type: string
          enum:
            - http
            - https
        http_host:
          type: string
      additionalProperties: false
      required:
        - name
        - model
  overrides:
    type: object
    properties:
      prompt_target_intent_matching_threshold:
        type: number
      optimize_context_window:
        type: boolean
  system_prompt:
    type: string
  prompt_targets:
    type: array
    items:
      type: object
      properties:
        name:
          type: string
        default:
          type: boolean
        description:
          type: string
        auto_llm_dispatch_on_response:
          type: boolean
        parameters:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              additionalProperties: false
              required:
                type: boolean
              default:
                anyOf:
                  - type: string
                  - type: integer
                  - type: boolean
              description:
                type: string
              type:
                type: string
              enum:
                type: array
                items:
                  anyOf:
                    - type: string
                    - type: integer
                    - type: boolean
              in_path:
                type: boolean
              format:
                type: string
            additionalProperties: false
            required:
              - name
              - description
              - type
        endpoint:
          type: object
          properties:
            name:
              type: string
            path:
              type: string
            http_method:
              type: string
              enum:
                - GET
                - POST
            http_headers:
              type: object
              additionalProperties:
                type: string
          additionalProperties: false
          required:
            - name
            - path
        system_prompt:
          type: string
      additionalProperties: false
      required:
        - name
        - description
  ratelimits:
    type: array
    items:
      type: object
      properties:
        model:
          type: string
        selector:
          type: object
          properties:
            key:
              type: string
            value:
              type: string
          additionalProperties: false
          required:
            - key
            - value
        limit:
          type: object
          properties:
            tokens:
              type: integer
            unit:
              type: string
          additionalProperties: false
          required:
            - tokens
            - unit
      additionalProperties: false
      required:
        - model
        - selector
        - limit
  tracing:
    type: object
    properties:
      random_sampling:
        type: integer
      trace_arch_internal:
        type: boolean
      additionalProperties: false
  mode:
    type: string
    enum:
      - llm
      - prompt
  prompt_guards:
    type: object
    properties:
      input_guards:
        type: object
        properties:
          jailbreak:
            type: object
            properties:
              on_exception:
                type: object
                properties:
                  message:
                    type: string
                additionalProperties: false
                required:
                  - message
            additionalProperties: false
            required:
              - on_exception
        additionalProperties: false
        required:
          - jailbreak
additionalProperties: false
required:
  - version
  - llm_providers
